# Generated by Django 5.2.4 on 2025-08-04 15:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name="O'yin nomi")),
                ('game_type', models.CharField(choices=[('Test', 'Test'), ('Tarjima', 'Tarjima'), ('To_g_ri_variant', "To'g'ri variantni tanlash")], max_length=20, verbose_name="O'yin turi")),
                ('reward_points', models.PositiveIntegerField(default=10, verbose_name='Mukofot ballari')),
                ('is_active', models.BooleanField(default=True, verbose_name='Faollik')),
            ],
            options={
                'verbose_name': "O'yin",
                'verbose_name_plural': "O'yinlar",
            },
        ),
        migrations.CreateModel(
            name='GameQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.TextField(verbose_name='Savol')),
                ('correct_answer', models.CharField(max_length=500, verbose_name="To'g'ri javob")),
                ('options', models.JSONField(help_text='Masalan: ["Variant1", "Variant2", "Variant3"]', verbose_name='Variantlar (JSON list)')),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='games.game', verbose_name="Qaysi o'yinga tegishli")),
            ],
            options={
                'verbose_name': "O'yin savoli",
                'verbose_name_plural': "O'yin savollari",
            },
        ),
    ]
