# Generated by Django 5.2.4 on 2025-08-04 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Sarlavha')),
                ('short_description', models.CharField(max_length=500, verbose_name='Qisqacha tavsif')),
                ('content', models.TextField(verbose_name='Asosiy matn')),
                ('image', models.ImageField(blank=True, null=True, upload_to='blog/images/', verbose_name='Rasm')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan sana')),
                ('is_published', models.BooleanField(default=True, verbose_name='Nashr qilinganmi')),
            ],
            options={
                'verbose_name': 'Blog maqolasi',
                'verbose_name_plural': 'Blog maqolalari',
                'ordering': ['-created_at'],
            },
        ),
    ]
