# Generated by Django 5.2.4 on 2025-08-04 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ChatHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prompt', models.TextField(verbose_name='Foydalanuvchi savoli (Prompt)')),
                ('response', models.TextField(verbose_name='AI javobi (Response)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan sana')),
            ],
            options={
                'verbose_name': 'Suhbat tarixi',
                'verbose_name_plural': 'Suhbatlar tarixi',
                'ordering': ['-created_at'],
            },
        ),
    ]
