# Generated by Django 5.2.4 on 2025-08-04 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AboutPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Sarlavha')),
                ('content', models.TextField(verbose_name='Asosiy matn')),
                ('team_members', models.JSONField(blank=True, help_text='Masalan: [{"name": "John Doe", "role": "CEO"}]', null=True, verbose_name="Jamoa a'zolari (JSON)")),
            ],
            options={
                'verbose_name': 'Biz haqimizda sahifasi',
                'verbose_name_plural': 'Biz haqimizda sahifalari',
            },
        ),
    ]
