# Generated by Django 5.2.4 on 2025-08-04 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Kurs nomi')),
                ('description', models.TextField(verbose_name='Tavsifi')),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Narxi')),
                ('level', models.CharField(choices=[('Beginner', 'Beginner'), ('Intermediate', 'Intermediate'), ('Advanced', 'Advanced'), ('IELTS-ready', 'IELTS-ready')], default='Beginner', max_length=20, verbose_name='Bosqich')),
                ('is_active', models.BooleanField(default=True, verbose_name='Faollik')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan sana')),
            ],
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Dars nomi')),
                ('content', models.TextField(verbose_name='Dars mazmuni')),
                ('video_file', models.FileField(blank=True, null=True, upload_to='lessons/videos/', verbose_name='Video fayl (yuklangan)')),
                ('video_link', models.URLField(blank=True, null=True, verbose_name='Video link (YouTube yoki boshqa)')),
                ('files', models.FileField(blank=True, null=True, upload_to='lessons/files/', verbose_name="Qo'shimcha fayllar (PDF)")),
                ('order_number', models.PositiveIntegerField(verbose_name='Tartib raqami')),
            ],
            options={
                'verbose_name': 'Dars',
                'verbose_name_plural': 'Darslar',
                'ordering': ['order_number'],
            },
        ),
        migrations.CreateModel(
            name='UserCourse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purchase_date', models.DateTimeField(auto_now_add=True, verbose_name='Xarid sanasi')),
            ],
            options={
                'verbose_name': 'Sotib olingan kurs',
                'verbose_name_plural': 'Sotib olingan kurslar',
            },
        ),
    ]
